name: safenotes_nord_theme
description: An arctic, north-bluish theme for Flutter, based on the Nord theme.
version: 3.0.0
repository: https://github.com/keshav-space/safenotes-nord-theme

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
